runtime: nodejs20
env: standard

handlers:
  - url: /.*
    script: auto

env_variables:
  APP_ID: "app.socian.community"
  AWS_ACCESS_KEY_ID: "AKIA4RCAOUWEKEWPZKAK"
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET_NAME: "beyondtheclass-bucket-mumbai"
  AWS_S3_IMAGE_BUCKET_NAME: "images-beyondtheclass-bucket-mumbai"


  # AWS_S3_BUCKET_NAME: "app.socian.bucket"
  # AWS_S3_IMAGE_BUCKET_NAME: "app.socian.bucket.data"
  # MONGO_DB_URI: "mongodb+srv://bilalillahi25:1J5i6aLc7Ouo78tD@cluster0.28el64s.mongodb.net/prod_v1_Socian?retryWrites=true&w=majority&appName=Cluster0"
  


  AWS_SECRET_ACCESS_KEY: "IQyLl0e61znMkfxjkSQqc8Vl6IVGdZvhNrykG8Uj"
  BACKEND_URL: "https://api.socian.app"
  CLIENT_ID: "1076027750526-li5gkit9klq06mmocutusfb6ta8e1etc.apps.googleusercontent.com"
  CLIENT_SECRET: "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"
  FRONTEND_URL: "https://www.socian.app"
  HTTP_ONLY: "true"
  JWT_ACCESS_EXPIRY_TIME: "1d"
  JWT_REFRESH_EXPIRY_TIME: "7d"
  JWT_SECRET: "de7350f2922cb3c1b9197cvkjds9843ogj4whg8p?<>v-dc123efgbli67wvjhwdccsd4399vjkvsv3530fc3ed6dd970081"
  MONGO_DB_URI: "mongodb+srv://bilalillahi25:1J5i6aLc7Ouo78tD@cluster0.28el64s.mongodb.net/test_BeyondTheClass?retryWrites=true&w=majority&appName=Cluster0"
  NODE_ENV: "production"
  OTP_COOLDOWN_PERIOD: "60000"
  OTP_RESEND_LIMIT: "3"
  PORT: "8080"
  REDIS_URL: ""
  RESAVE: "false"
  resend: "re_FfzYTszB_FELCFSeePgkQD5wYcENrXHah"
  ROLLING: "true"
  RUN_LIMITER: "false"
  SAVE_UNINTIALIZED: "false"
  SESSION_SECRET: "k78UF7uf68FU8$%£*&CHG"
  VITE_API_URL: "https://api.socian.app"
  VITE_GOOGLE_MAPS_API_KEY: "AIzaSyBeoimjSiMUby139D2f1wFsLHxBmNWNcI4"
  GOOGLE_GEMINI_KEY: "AIzaSyDFJHSq1rZwf6B6TwcQ-nbNdUltWJzy2VM"

# use this for online
  VALKEY: "rediss://default:AVNS__0-UfuASPDYL_WsT_Cp@valkey-beyondtheclass-beyondtheclass.j.aivencloud.com:28943"
# us below at local
  VALKEY_HOST: "valkey-beyondtheclass-beyondtheclass.j.aivencloud.com"
  VALKEY_PORT: "28943"
  VALKEY_USERNAME: "default"
  VALKEY_PASSWORD: "AVNS__0-UfuASPDYL_WsT_Cp"


  VALKEY2: "rediss://default:AVNS_wk3UwK-mGCSTtl_5pMg@btc-2-btc-2.l.aivencloud.com:18202"


  NEW_AZURE_CONECTION_STRING: "com-beyondtheclass.redis.cache.windows.net:6380,password=AB7sAtlqJ2TYaLhjjpCIqr3Q2Mu0iSTtWAzCaPXJD4U=,ssl=True,abortConnect=False"

  NEW_AZURE_REDISHOST: "com-beyondtheclass.redis.cache.windows.net"
  NEW_AZURE_REDISPORT: "6380"
  NEW_AZURE_REDISPASSWORD: "AB7sAtlqJ2TYaLhjjpCIqr3Q2Mu0iSTtWAzCaPXJD4U="



  KAFKA_BROKER: "kafka-beyondtheclass.servicebus.windows.net:9093"
  SAS_USERNAME: "$ConnectionString"
  SAS_PASSWORD: "Endpoint=sb://kafka-beyondtheclass.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=HWpYVZwLZnfPqCpBoz8/B1xufp6Be28Iz+AEhMu3RA0="
  RESEND_SIGNING_SECRET: "whsec_fBpHcvoh55mQkVsPdZOhvoOx/5G5bfm3"